import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const mode=process.argv[2];
if(!['local','remote'].includes(mode))throw Error('Usage: node tools/configure.mjs local|remote');
const c=JSON.parse(fs.readFileSync(path.join(root,`config.private.${mode}.json`),'utf8'));
for(const key of ['ERP_URL','ERP_USER','ERP_API_KEY','ERP_API_SECRET','COMPANY','CURRENCY'])if(!c[key]||String(c[key]).includes('<'))throw Error(`Fill ${key} first`);
const runtime=path.join(root,'.runtime',mode);
if(fs.existsSync(runtime))throw Error('Runtime already exists. Keep it; use a new project copy for changed credentials, or review/update its files manually.');
process.umask(0o077);
fs.mkdirSync(runtime,{recursive:true,mode:0o700});
fs.mkdirSync(path.join(runtime,'workspace'),{mode:0o700});
const profile={principal:'project-1-1-reader',erpUser:c.ERP_USER,scope:'overridden-by-verified-erp-origin',company:c.COMPANY,currency:c.CURRENCY,maxAmount:0,suppliers:[],docTypes:['Item','Sales Order','Sales Invoice'],reports:[],actions:['erp.query','erp.get']};
fs.writeFileSync(path.join(runtime,'profile.json'),JSON.stringify(profile,null,2),{mode:0o600});
const env={ERP_URL:c.ERP_URL,ERP_API_KEY:c.ERP_API_KEY,ERP_API_SECRET:c.ERP_API_SECRET,ERP_PROFILE_FILE:path.join(runtime,'profile.json'),ERP_STATE_DB:path.join(runtime,'erp.sqlite'),ERP_ALLOW_LOCAL_HTTP:mode==='local'?'1':'0',ERP_FAKE:'0',SEND_LANGFUSE:'0'};
fs.writeFileSync(path.join(runtime,'erp.env'),Object.entries(env).map(([k,v])=>`${k}=${JSON.stringify(v)}`).join('\n')+'\n',{mode:0o600});
const mcp={mcpServers:{'project-1-1-erp':{command:process.execPath,args:[path.join(root,'tools/mcp-entry.mjs'),path.join(runtime,'erp.env'),path.join(root,'backend/erp/server.mjs')],include_tools:['erp.query','erp.get'],requires_approval:true}}};
fs.writeFileSync(path.join(runtime,'mcp.json'),JSON.stringify(mcp,null,2),{mode:0o600});
console.log('Prepared isolated state directory:',runtime);
console.log('Use this exact COWORKER_STATE_DIR for both server and GUI. No model key has been configured.');
